<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4019.2">
  <POU Name="MAIN" Id="{d25881fd-bae0-4e0a-b3eb-c173027ef094}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[.Global_Variables.TcJoy();

IF .Global_Variables.TcJoy.bIsActive THEN
	;
END_IF]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>